[manager]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = true

[preview]
max_width = 600
max_height = 900

[opener]
edit = [
  { run = '${EDITOR:-vim} "$@"', block = true, for = "unix" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "code" },
]
